server: 
  port: 8091 
logging:
    level: 
        org.springframework: info
        data: DEBUG
        security: DEBUG
    config: classpath:logback-spring.xml
spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  mvc:
    static-path-pattern: /**
  thymeleaf: 
    servlet:
      content-type: text/html
    encoding: UTF-8
    cache: false
  datasource: 
         type: com.alibaba.druid.pool.DruidDataSource
         url: jdbc:mysql://localhost:3306/mayday?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
         username: root
         password: root
         driver-class-name: com.mysql.jdbc.Driver
mybatis: 
  typeAliasesPackage: com.songhaozhi.mayday.model.domain
  mapperLocations: classpath:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper: 
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

sso:
  BaseUrl: http://172.16.5.4:10005

access:
  appid: cpk.sws.appid1
  secret: C0F48FC8-EC67-4faa-97E6-A9903F5E74AC
  url: http://172.16.5.4:10005/api/uaa/oauth/token